version: '1'

services:
  web:
    image: nginx:latest
    ports:
      - "8054:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

  app:
    image: warehouse:latest
    ports:
      - "5000:5000"
    environment:
      - ENV_VARIABLE=value
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=jdbc:mysql://localhost:3306/warehouse
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
